## 1.	Create a 2D array and print the dim and shape

In [14]:
import numpy as np

In [6]:
arry=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arry.shape

(2, 5)

In [7]:
arry.ndim

2

## 2.	Create an array of 20 numbers using arange function and slice the values between 10 to 15

In [28]:
arr=np.arange(0,21) #array creation from 0 to 20 ele
print("ELe from 0 to 1 in array:",arr)
arr2=slice(10,15,1) #slicing the array
print("Slicing from 10 to 15: ",arr[arr2])

ELe from 0 to 1 in array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Slicing from 10 to 15:  [10 11 12 13 14]


## 3.	Create 2 arrays of 7X5 dimension and broadcast between the 2 arrays using 

In [31]:
#Array creation 7*5
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10],[2,4,6,8,2],[1,3,5,7,9],[1,2,4,5,6],[2,3,5,7,8],[1,10,2,20,30]])
arr2=np.array([[0,1,1,2,5],[3,5,4,6,1],[2,5,7,8,9],[0,1,5,4,3],[5,25,12,10,8],[12,13,15,1,2],[1,0,2,22,31]])
add=arr1+arr2 #addition
print("Addition of 2 arrays:",add)
sub=arr1-arr2
print("Subtraction of 2 arrays:",sub)
mul=arr1*arr2
print("Multiplication of 2 arrays:",mul)
div=arr1//arr2
print("Division1 of 2 arrays:",div) #divide by zero error encoutered as arr2 has 0 in the array

div2=arr2//arr1
print("Division2 of 2 arrays:",div2)

Addition of 2 arrays: [[ 1  3  4  6 10]
 [ 9 12 12 15 11]
 [ 4  9 13 16 11]
 [ 1  4 10 11 12]
 [ 6 27 16 15 14]
 [14 16 20  8 10]
 [ 2 10  4 42 61]]
Subtraction of 2 arrays: [[  1   1   2   2   0]
 [  3   2   4   3   9]
 [  0  -1  -1   0  -7]
 [  1   2   0   3   6]
 [ -4 -23  -8  -5  -2]
 [-10 -10 -10   6   6]
 [  0  10   0  -2  -1]]
Multiplication of 2 arrays: [[  0   2   3   8  25]
 [ 18  35  32  54  10]
 [  4  20  42  64  18]
 [  0   3  25  28  27]
 [  5  50  48  50  48]
 [ 24  39  75   7  16]
 [  1   0   4 440 930]]
Division1 of 2 arrays: [[ 0  2  3  2  1]
 [ 2  1  2  1 10]
 [ 1  0  0  1  0]
 [ 0  3  1  1  3]
 [ 0  0  0  0  0]
 [ 0  0  0  7  4]
 [ 1  0  1  0  0]]
Division2 of 2 arrays: [[ 0  0  0  0  1]
 [ 0  0  0  0  0]
 [ 1  1  1  1  4]
 [ 0  0  1  0  0]
 [ 5 12  3  2  1]
 [ 6  4  3  0  0]
 [ 1  0  1  1  1]]


C:\Users\Prasana\AppData\Local\Temp/ipykernel_8924/3631994833.py:10: RuntimeWarning: divide by zero encountered in floor_divide
  div=arr1//arr2


## 4.	Create 2 incompatible arrays for broadcast and print out the error

In [35]:
#array with 2*3 dim
ar=np.array([[1,2,3],[4,5,6]])
ar.ndim
#array with 2*4
ar2=np.array([[5,6,9,8],[1,5,9,7]])
ar2.ndim

#broadcasting with different ele
ar*ar2


ValueError: operands could not be broadcast together with shapes (2,3) (2,4) 

## 5.	Create two arrays of any dimension and perform vstack and hstack

In [40]:
#creation of2 arrays
a=np.array([[2,4,6],[3,6,9]])
b=np.array([[1,2,3],[4,5,6]])

print("Stack operation:")
np.stack((a,b),axis=1)





Stack operation:


array([[[2, 4, 6],
        [1, 2, 3]],

       [[3, 6, 9],
        [4, 5, 6]]])

In [42]:
#vstack opeation
print("VStack operation:")
np.vstack((a,b))

VStack operation:


array([[2, 4, 6],
       [3, 6, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [43]:
#hstack operation
print("hStack operation:")
np.hstack((a,b))

hStack operation:


array([[2, 4, 6, 1, 2, 3],
       [3, 6, 9, 4, 5, 6]])

## 6.	Append two arrays using axis = 0 and axis = 1


In [6]:
array1=np.array([[10,20,10,30,40,50],[1,2,5,50,60,40]])
array1

array([[10, 20, 10, 30, 40, 50],
       [ 1,  2,  5, 50, 60, 40]])

In [8]:
np.append(array1,[[2,3],[9,8]],axis=1)


array([[10, 20, 10, 30, 40, 50,  2,  3],
       [ 1,  2,  5, 50, 60, 40,  9,  8]])

In [9]:
array1

array([[10, 20, 10, 30, 40, 50],
       [ 1,  2,  5, 50, 60, 40]])

In [10]:
np.append(array1,[[2,3,4,5,6,7],[9,8,10,11,12,13]],axis=0)

array([[10, 20, 10, 30, 40, 50],
       [ 1,  2,  5, 50, 60, 40],
       [ 2,  3,  4,  5,  6,  7],
       [ 9,  8, 10, 11, 12, 13]])

## 7.	Create a dataframe for 8 X 4 dimension using list of lists and name the columns while dataframe creation

In [9]:
import pandas as pd

In [15]:
df=pd.DataFrame() #creating df without any columns and rows

In [16]:
print(df)

Empty DataFrame
Columns: []
Index: []


In [17]:
#creating df using list
list1=list(range(8))
df=pd.DataFrame(list1)
df

0
0  0
1  1
2  2
3  3
4  4
5  5
6  6
7  7

In [18]:
#creating df with column name 

l2=[['BMW','Petrol','Blue','2'],['Audi','Petrol','Black','5'],['Benz','Diesel','Red','5'],['Tata','gas','White','8'],['Maruthi','Petrol','Grey','5'],['Ford','gas','DarkBlue','8'],['Hyundai','Diesel','White','5'],['Skoda','Petrol','Black','5']]
df=pd.DataFrame(l2,columns=['CompanyName','Enginetype','Color','NoofSeater'])
df

CompanyName Enginetype     Color NoofSeater
0         BMW     Petrol      Blue          2
1        Audi     Petrol     Black          5
2        Benz     Diesel       Red          5
3        Tata        gas     White          8
4     Maruthi     Petrol      Grey          5
5        Ford        gas  DarkBlue          8
6     Hyundai     Diesel     White          5
7       Skoda     Petrol     Black          5

## 8.	Create a dataframe of 4 X 8 dimension using a dictionary

In [27]:
dict1={'class':[6,7,8,9,10,11,12,13],'Cricketplayer':[20,22,23,21,25,28,32,34],'Hockeyplayer':[10,12,14,13,16,17,15,16],'Athlete':[11,12,13,19,18,20,23,22]}
df=pd.DataFrame(dict1)
df

class  Cricketplayer  Hockeyplayer  Athlete
0      6             20            10       11
1      7             22            12       12
2      8             23            14       13
3      9             21            13       19
4     10             25            16       18
5     11             28            17       20
6     12             32            15       23
7     13             34            16       22

## 9.	Use loc and iloc to subset the data for the above dataframe

In [28]:
df.loc[:3]

class  Cricketplayer  Hockeyplayer  Athlete
0      6             20            10       11
1      7             22            12       12
2      8             23            14       13
3      9             21            13       19

In [30]:
df.iloc[:5]

class  Cricketplayer  Hockeyplayer  Athlete
0      6             20            10       11
1      7             22            12       12
2      8             23            14       13
3      9             21            13       19
4     10             25            16       18

In [36]:
df.iloc[:4,:2]

class  Cricketplayer
0      6             20
1      7             22
2      8             23
3      9             21

## 10.	How to check the total number of not null values in a column?

In [38]:
df['class'].notnull()

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
Name: class, dtype: bool

## 11.	Create a dataframe with missing values and fill them all with 100

In [91]:
# for creating a missing value using new  df 
df12 = pd.DataFrame(np.random.randn(3, 3), index = ['1','3','5'], columns= ['ClassA', 'ClassB', 'ClassC'])
df12


ClassA    ClassB    ClassC
1  0.347229 -0.964296  2.113712
3 -0.013251  0.266314 -0.350594
5  0.515890  0.909068 -0.665133

In [93]:
df12 = df12.reindex(['1', '2', '3', '4', '5','6'])
df12

ClassA    ClassB    ClassC
1  0.347229 -0.964296  2.113712
2       NaN       NaN       NaN
3 -0.013251  0.266314 -0.350594
4       NaN       NaN       NaN
5  0.515890  0.909068 -0.665133
6       NaN       NaN       NaN

In [94]:
df12.fillna(100, inplace=True)
df12



ClassA      ClassB      ClassC
1    0.347229   -0.964296    2.113712
2  100.000000  100.000000  100.000000
3   -0.013251    0.266314   -0.350594
4  100.000000  100.000000  100.000000
5    0.515890    0.909068   -0.665133
6  100.000000  100.000000  100.000000

## 12.	Create a dataframe with missing values and drop the null records

In [7]:
dictmiss = {'id': [1, 2, 3, 4, 5],
      'Name': ['Anbu', 'Baky', 'Saro', np.NaN, 'casu'],
      'Team': ['red', np.NaN, 'blue', 'blue', 'yellow']}   #dictonary
dictmiss

{'id': [1, 2, 3, 4, 5],
 'Name': ['Anbu', 'Baky', 'Saro', nan, 'casu'],
 'Team': ['red', nan, 'blue', 'blue', 'yellow']}

In [11]:
dataframem=pd.DataFrame(dictmiss)
dataframem.dropna()


id  Name    Team
0   1  Anbu     red
2   3  Saro    blue
4   5  casu  yellow

In [16]:
dictmiss1 = {'id': [1, 2, 3, 4, 5,6,7],
      'Name': ['Anbu', 'Baky', 'Saro', np.NaN, 'casu','Dark','Ximy'],
      'Team': ['red', np.NaN, 'blue', 'blue', 'yellow',np.NaN,'green']}   #dictonary
dictmiss1

{'id': [1, 2, 3, 4, 5, 6, 7],
 'Name': ['Anbu', 'Baky', 'Saro', nan, 'casu', 'Dark', 'Ximy'],
 'Team': ['red', nan, 'blue', 'blue', 'yellow', nan, 'green']}

In [17]:
dataframem=pd.DataFrame(dictmiss)
dataframem.dropna(axis=1)   #dropping columns which has aleast one missing value

id
0   1
1   2
2   3
3   4
4   5

In [20]:
dataframem.dropna(how='all') #row which has all the data are null , here no row is deleted

id  Name    Team
0   1  Anbu     red
1   2  Baky     NaN
2   3  Saro    blue
3   4   NaN    blue
4   5  casu  yellow

In [21]:
dataframem.dropna(how='any') #row which has atleast one data as null , 2 rows are droped

id  Name    Team
0   1  Anbu     red
2   3  Saro    blue
4   5  casu  yellow

## 13.	Perform following aggregation task on below table
### a.	Get the average age group by Regrion


In [25]:
Agglist = {'Age': [25, 30, 45, 35, 33, 35, 25, 52, 21, 24, 48, 22, 27, 28, 21, 51, 23],
 'Hair Colour': ['Black', 'Black', 'Red', 'Blond', 'Brown', 'Brown', 'Black', 'Brown', 'Blond', 'Blond', 'Black', 'Black',
                 'Brown', 'Black', 'Blond', 'Black', 'Brown'],
 'US Region': ['Southwest', 'Northwest', 'Northeast', 'Southwest', 'Southwest', 'Northeast', 'Southwest', 'Southeast', 'Southwest',
               'Northeast', 'Southwest', 'Southwest', 'Northeast', 'Southeast', 'Southeast', 'Northwest', 'Southeast'],
 'Validation': [1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1]
}


dfAgglist=pd.DataFrame(Agglist)
dfAgglist

Age Hair Colour  US Region  Validation
0    25       Black  Southwest           1
1    30       Black  Northwest           1
2    45         Red  Northeast           1
3    35       Blond  Southwest           0
4    33       Brown  Southwest           0
5    35       Brown  Northeast           0
6    25       Black  Southwest           0
7    52       Brown  Southeast           0
8    21       Blond  Southwest           1
9    24       Blond  Northeast           0
10   48       Black  Southwest           1
11   22       Black  Southwest           0
12   27       Brown  Northeast           0
13   28       Black  Southeast           1
14   21       Blond  Southeast           1
15   51       Black  Northwest           0
16   23       Brown  Southeast           1

In [29]:
dfres=dfAgglist.mean(axis=0) #Avg of each column
dfres

C:\Users\Prasana\AppData\Local\Temp/ipykernel_3156/2294229854.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  dfres=dfAgglist.mean(axis=0)


Age           32.058824
Validation     0.470588
dtype: float64

In [30]:
dfres1=dfAgglist[['Age']].mean(axis=0) #Avg of age column
dfres1

Age    32.058824
dtype: float64

In [39]:
dfres5=dfAgglist.groupby(['US Region'])['Age'].mean() #Avg of age column by region
dfres5

US Region
Northeast    32.750000
Northwest    40.500000
Southeast    31.000000
Southwest    29.857143
Name: Age, dtype: float64

## b.	Get the sum of Age and Validation group by Hair color and then reset the index

In [35]:
import warnings
warnings.filterwarnings('ignore')

In [36]:
dfres2=dfAgglist.groupby('Hair Colour',as_index=False)['Age','Validation'].sum()   #performng groupby and sum on two columns 
dfres2  # to reset ndex using as_index

Hair Colour  Age  Validation
0       Black  229           4
1       Blond  101           2
2       Brown  170           1
3         Red   45           1

In [37]:
dfres3=dfAgglist.groupby('Hair Colour')['Age','Validation'].sum().reset_index()   #using reset_indexing
dfres3

Hair Colour  Age  Validation
0       Black  229           4
1       Blond  101           2
2       Brown  170           1
3         Red   45           1

## c.	Get the mean and the median of Age group by Region

In [41]:
dfres5=dfAgglist.groupby(['US Region'])['Age'].mean() #Avg of age column by region
dfres5


US Region
Northeast    32.750000
Northwest    40.500000
Southeast    31.000000
Southwest    29.857143
Name: Age, dtype: float64

In [42]:
dfres6=dfAgglist.groupby(['US Region'])['Age'].median() #Avg of age column by region
dfres6

US Region
Northeast    31.0
Northwest    40.5
Southeast    25.5
Southwest    25.0
Name: Age, dtype: float64

## 14.	Split the below table into half and perform merge (inner, left and right) on Region. One example for each type of merge (inner, left and right)

In [44]:
dfs_1 = dfAgglist.iloc[:9,:]   #using iloc splitting dataframe into 2 
dfs_1

Age Hair Colour  US Region  Validation
0   25       Black  Southwest           1
1   30       Black  Northwest           1
2   45         Red  Northeast           1
3   35       Blond  Southwest           0
4   33       Brown  Southwest           0
5   35       Brown  Northeast           0
6   25       Black  Southwest           0
7   52       Brown  Southeast           0
8   21       Blond  Southwest           1

In [45]:
dfs_2right = dfAgglist.iloc[9:,:]
dfs_2right

Age Hair Colour  US Region  Validation
9    24       Blond  Northeast           0
10   48       Black  Southwest           1
11   22       Black  Southwest           0
12   27       Brown  Northeast           0
13   28       Black  Southeast           1
14   21       Blond  Southeast           1
15   51       Black  Northwest           0
16   23       Brown  Southeast           1

In [46]:
#Merge inner
df_inner_join= pd.merge(dfs_1, dfs_2right, on='US Region', how='inner')
df_inner_join

Age_x Hair Colour_x  US Region  Validation_x  Age_y Hair Colour_y  \
0      25         Black  Southwest             1     48         Black   
1      25         Black  Southwest             1     22         Black   
2      35         Blond  Southwest             0     48         Black   
3      35         Blond  Southwest             0     22         Black   
4      33         Brown  Southwest             0     48         Black   
5      33         Brown  Southwest             0     22         Black   
6      25         Black  Southwest             0     48         Black   
7      25         Black  Southwest             0     22         Black   
8      21         Blond  Southwest             1     48         Black   
9      21         Blond  Southwest             1     22         Black   
10     30         Black  Northwest             1     51         Black   
11     45           Red  Northeast             1     24         Blond   
12     45           Red  Northeast             1     27         Brown   
13     35         Brown  Northeast             0     24         Blond   
14     35         Brown  Northeast             0     27         Brown   
15     52         Brown  Southeast             0     28         Black   
16     52         Brown  Southeast             0     21         Blond   
17     52         Brown  Southeast             0     23         Brown   

    Validation_y  
0              1  
1              0  
2              1  
3              0  
4              1  
5              0  
6              1  
7              0  
8              1  
9              0  
10             0  
11             0  
12             0  
13             0  
14             0  
15             1  
16             1  
17             1

In [47]:
#Merge left
left_join_df= pd.merge(dfs_1, dfs_2right, on='US Region', how='left')
left_join_df 

Age_x Hair Colour_x  US Region  Validation_x  Age_y Hair Colour_y  \
0      25         Black  Southwest             1     48         Black   
1      25         Black  Southwest             1     22         Black   
2      30         Black  Northwest             1     51         Black   
3      45           Red  Northeast             1     24         Blond   
4      45           Red  Northeast             1     27         Brown   
5      35         Blond  Southwest             0     48         Black   
6      35         Blond  Southwest             0     22         Black   
7      33         Brown  Southwest             0     48         Black   
8      33         Brown  Southwest             0     22         Black   
9      35         Brown  Northeast             0     24         Blond   
10     35         Brown  Northeast             0     27         Brown   
11     25         Black  Southwest             0     48         Black   
12     25         Black  Southwest             0     22         Black   
13     52         Brown  Southeast             0     28         Black   
14     52         Brown  Southeast             0     21         Blond   
15     52         Brown  Southeast             0     23         Brown   
16     21         Blond  Southwest             1     48         Black   
17     21         Blond  Southwest             1     22         Black   

    Validation_y  
0              1  
1              0  
2              0  
3              0  
4              0  
5              1  
6              0  
7              1  
8              0  
9              0  
10             0  
11             1  
12             0  
13             1  
14             1  
15             1  
16             1  
17             0

In [48]:
#Merge Right
left_join_df= pd.merge(dfs_1, dfs_2right, on='US Region', how='right')
left_join_df 

Age_x Hair Colour_x  US Region  Validation_x  Age_y Hair Colour_y  \
0      45           Red  Northeast             1     24         Blond   
1      35         Brown  Northeast             0     24         Blond   
2      25         Black  Southwest             1     48         Black   
3      35         Blond  Southwest             0     48         Black   
4      33         Brown  Southwest             0     48         Black   
5      25         Black  Southwest             0     48         Black   
6      21         Blond  Southwest             1     48         Black   
7      25         Black  Southwest             1     22         Black   
8      35         Blond  Southwest             0     22         Black   
9      33         Brown  Southwest             0     22         Black   
10     25         Black  Southwest             0     22         Black   
11     21         Blond  Southwest             1     22         Black   
12     45           Red  Northeast             1     27         Brown   
13     35         Brown  Northeast             0     27         Brown   
14     52         Brown  Southeast             0     28         Black   
15     52         Brown  Southeast             0     21         Blond   
16     30         Black  Northwest             1     51         Black   
17     52         Brown  Southeast             0     23         Brown   

    Validation_y  
0              0  
1              0  
2              1  
3              1  
4              1  
5              1  
6              1  
7              0  
8              0  
9              0  
10             0  
11             0  
12             0  
13             0  
14             1  
15             1  
16             0  
17             1

## 15.	Split the below table and perform concat row wise and column wise

In [49]:
dfs_concat = pd.concat([dfs_1, dfs_2right])
dfs_concat


Age Hair Colour  US Region  Validation
0    25       Black  Southwest           1
1    30       Black  Northwest           1
2    45         Red  Northeast           1
3    35       Blond  Southwest           0
4    33       Brown  Southwest           0
5    35       Brown  Northeast           0
6    25       Black  Southwest           0
7    52       Brown  Southeast           0
8    21       Blond  Southwest           1
9    24       Blond  Northeast           0
10   48       Black  Southwest           1
11   22       Black  Southwest           0
12   27       Brown  Northeast           0
13   28       Black  Southeast           1
14   21       Blond  Southeast           1
15   51       Black  Northwest           0
16   23       Brown  Southeast           1

In [50]:
dfs_reindex = pd.concat([dfs_1, dfs_2right], ignore_index=True)  #reindexing in concat
dfs_reindex


Age Hair Colour  US Region  Validation
0    25       Black  Southwest           1
1    30       Black  Northwest           1
2    45         Red  Northeast           1
3    35       Blond  Southwest           0
4    33       Brown  Southwest           0
5    35       Brown  Northeast           0
6    25       Black  Southwest           0
7    52       Brown  Southeast           0
8    21       Blond  Southwest           1
9    24       Blond  Northeast           0
10   48       Black  Southwest           1
11   22       Black  Southwest           0
12   27       Brown  Northeast           0
13   28       Black  Southeast           1
14   21       Blond  Southeast           1
15   51       Black  Northwest           0
16   23       Brown  Southeast           1

In [51]:
dfs_concatrow = pd.concat([dfs_1, dfs_2right], axis=1)
dfs_concatrow

Age Hair Colour  US Region  Validation   Age Hair Colour  US Region  \
0   25.0       Black  Southwest         1.0   NaN         NaN        NaN   
1   30.0       Black  Northwest         1.0   NaN         NaN        NaN   
2   45.0         Red  Northeast         1.0   NaN         NaN        NaN   
3   35.0       Blond  Southwest         0.0   NaN         NaN        NaN   
4   33.0       Brown  Southwest         0.0   NaN         NaN        NaN   
5   35.0       Brown  Northeast         0.0   NaN         NaN        NaN   
6   25.0       Black  Southwest         0.0   NaN         NaN        NaN   
7   52.0       Brown  Southeast         0.0   NaN         NaN        NaN   
8   21.0       Blond  Southwest         1.0   NaN         NaN        NaN   
9    NaN         NaN        NaN         NaN  24.0       Blond  Northeast   
10   NaN         NaN        NaN         NaN  48.0       Black  Southwest   
11   NaN         NaN        NaN         NaN  22.0       Black  Southwest   
12   NaN         NaN        NaN         NaN  27.0       Brown  Northeast   
13   NaN         NaN        NaN         NaN  28.0       Black  Southeast   
14   NaN         NaN        NaN         NaN  21.0       Blond  Southeast   
15   NaN         NaN        NaN         NaN  51.0       Black  Northwest   
16   NaN         NaN        NaN         NaN  23.0       Brown  Southeast   

    Validation  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  
5          NaN  
6          NaN  
7          NaN  
8          NaN  
9          0.0  
10         1.0  
11         0.0  
12         0.0  
13         1.0  
14         1.0  
15         0.0  
16         1.0