## 1.	Create a program that asks the user to enter their name and their age. Print out a message that tells them the year that they will turn 100 years old

In [3]:
name=input("Enter your name: ")
age=int(input("Enter your current age: "))
hunderth_year=2020+(100-age)
print("at your 100 , year is :",hunderth_year)

Enter your name: gowthami
Enter your current age: 25
at your 100 , year is : 2095


## 2.	What is pandas groupby? Demonstrate with your own example

In [ ]:
Pandas groupby will split the data into seperate groups and perform computation for better analysis 

In [2]:
import pandas as pd
import numpy as np

In [8]:
#creating dataframe with columns
dict1={'Age':[16,17,18,19,16,18,20,21],'Cricketplayer':[20,22,23,21,25,28,32,34],'Hockeyplayer':[10,12,14,13,16,17,15,16],'Athlete':[11,12,13,19,18,20,23,22]}
df=pd.DataFrame(dict1)
df

Age  Cricketplayer  Hockeyplayer  Athlete
0   16             20            10       11
1   17             22            12       12
2   18             23            14       13
3   19             21            13       19
4   16             25            16       18
5   18             28            17       20
6   20             32            15       23
7   21             34            16       22

In [9]:
df.groupby(['Age'])['Athlete'].sum()

Age
16    29
17    12
18    33
19    19
20    23
21    22
Name: Athlete, dtype: int64

## 3.	How to create a dataframe from list?

In [10]:
#creating df using list with columns 
l2=[['BMW','Petrol','Blue','2'],['Audi','Petrol','Black','5'],['Benz','Diesel','Red','5'],['Tata','gas','White','8'],['Maruthi','Petrol','Grey','5'],['Ford','gas','DarkBlue','8'],['Hyundai','Diesel','White','5'],['Skoda','Petrol','Black','5']]
df=pd.DataFrame(l2,columns=['CompanyName','Enginetype','Color','NoofSeater'])
df

CompanyName Enginetype     Color NoofSeater
0         BMW     Petrol      Blue          2
1        Audi     Petrol     Black          5
2        Benz     Diesel       Red          5
3        Tata        gas     White          8
4     Maruthi     Petrol      Grey          5
5        Ford        gas  DarkBlue          8
6     Hyundai     Diesel     White          5
7       Skoda     Petrol     Black          5

## 4.	What are the ways to combine the dataframe in pandas. Give an example for each

In [ ]:
Pandas provide Merge,Join and concat for easily combine dataframe with other sets.


In [13]:
#1. Merge Example
#creating 2 dataframe to  merge 

dataf1=pd.DataFrame({'CompanyName':['Tcs','Infosys','Oracle','L&T'],
                     'NoofBranch':[120,110,55,45],
                     'Companyid':[220,230,255,222],
                    'HeadQuater':['USA','Newjersy','UK','India']})

dataf2=pd.DataFrame({'CompanyName':['Tm','capgemini','Ett','Mindtree'],
                    'NoofBranch':[120,110,55,45],
                      'Companyid':[221,231,256,289],
                    'HeadQuater':['USA','Newjersy','UK','India']})
    



In [14]:
dataf1

CompanyName  NoofBranch  Companyid HeadQuater
0         Tcs         120        220        USA
1     Infosys         110        230   Newjersy
2      Oracle          55        255         UK
3         L&T          45        222      India

In [15]:
dataf2

CompanyName  NoofBranch  Companyid HeadQuater
0          Tm         120        221        USA
1   capgemini         110        231   Newjersy
2         Ett          55        256         UK
3    Mindtree          45        289      India

In [16]:
#merging with any one of the column key
pd.merge(dataf1,dataf2, on='NoofBranch')

CompanyName_x  NoofBranch  Companyid_x HeadQuater_x CompanyName_y  \
0           Tcs         120          220          USA            Tm   
1       Infosys         110          230     Newjersy     capgemini   
2        Oracle          55          255           UK           Ett   
3           L&T          45          222        India      Mindtree   

   Companyid_y HeadQuater_y  
0          221          USA  
1          231     Newjersy  
2          256           UK  
3          289        India

In [18]:
#Concat example
pd.concat([dataf1,dataf2], axis=1)

CompanyName  NoofBranch  Companyid HeadQuater CompanyName  NoofBranch  \
0         Tcs         120        220        USA          Tm         120   
1     Infosys         110        230   Newjersy   capgemini         110   
2      Oracle          55        255         UK         Ett          55   
3         L&T          45        222      India    Mindtree          45   

   Companyid HeadQuater  
0        221        USA  
1        231   Newjersy  
2        256         UK  
3        289      India

In [23]:
 #join example
    
left=pd.DataFrame({'ColA':[1,2,3,4],
                    'ColB':[5,6,7,8]})
right=pd.DataFrame({'ColC':[9,10,11,12],
                    'ColD':[15,16,17,8]})


In [24]:
left

ColA  ColB
0     1     5
1     2     6
2     3     7
3     4     8

In [25]:
right

ColC  ColD
0     9    15
1    10    16
2    11    17
3    12     8

In [26]:
res=left.join(right)   #join 

In [27]:
res

ColA  ColB  ColC  ColD
0     1     5     9    15
1     2     6    10    16
2     3     7    11    17
3     4     8    12     8

## 5.	What is the difference between list and tuples in Python?

1. List and tuple both are used to store collection of data.
2. Both are sequential datatype
3. Major difference is that tuples are immutable where list are mutable. Values in the list can be modified 
4. A List is an ordered collection of items that is separated by comma and enclosed in square brackets, it takes same or different datatypes.
5. Tuple is similar to list but only difference is that comma separated items of same or different type are enclosed in parentheses. It start with Zero index as list and string

In [28]:
#Example for list
List1=[10,20,30,40,"IndividualMark"]
List1

[10, 20, 30, 40, 'IndividualMark']

In [30]:
#example for tuple 
t1=(52,25,28,88,"Score")
t1

(52, 25, 28, 88, 'Score')

In [32]:
#trying to change list and tuple vlue 
List1[1]=70
List1

[10, 70, 30, 40, 'IndividualMark']

In [33]:
t1[1]=70
t1

TypeError: 'tuple' object does not support item assignment

In [ ]:
#Hence cannot change tuple value after instantiated.

## 6.	Find out the mean, median and standard deviation of this numpy array -> np.array([1,5,3,100,4,48])

In [34]:
arr1=np.array([1,5,3,100,4,48])
arr1

array([  1,   5,   3, 100,   4,  48])

In [35]:
#mean median and std 
print(np.mean(arr1,axis=0))
print(np.median(arr1,axis=0))
print(np.std(arr1,axis=0))

26.833333333333332
4.5
36.59424666377065


## 7.	How will you remove duplicate elements from a list?


In [36]:
#creating a list with duplicate ele 
li=[10,20,30,40,10,100,50,20]
li

[10, 20, 30, 40, 10, 100, 50, 20]

In [38]:
#Method 1 using unique function
finallist = pd.unique(li).tolist()
finallist

[10, 20, 30, 40, 100, 50]

In [39]:
#method2 using enum and list comprehension
enumlist = [i for j, i in enumerate(li) if i not in li[:j]] 
enumlist

[10, 20, 30, 40, 100, 50]

## 8.	What is a map() function in Python? Give an example

map() is used to execute the specified function each time using an iteator 
syntax: map(funct,para_value)

In [41]:
#example 
def myfunc(a, b):
    return a + b

mapvar= map(myfunc, ('1', '2', '3'), ('10', '20', '30'))
mapvar
print(list(mapvar))

['110', '220', '330']


## 9.	What is pass in Python?

1. Pass statement is used as a placeholder in the future use 
2. When empty code is executed in a loop or in code by using pass statement we can avoid getting error 


In [42]:
#example 
a = 10
b = 25

if b > a:    #here if is an empty statement if pass is not  used there will be an error 
  

IndentationError: expected an indented block (Temp/ipykernel_8108/455609592.py, line 6)

In [43]:
a = 10
b = 25

if b > a: #No error using pass. It just passes the cursor to next line of a code
    pass

## 10.	What is vstack() in numpy? Give an example

vstack() is used to stack the sequence of input arrays vertically and  to make the result as a single array.(row wise)

In [46]:
#example
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])


In [48]:
a.shape

(5,)

In [49]:
b.shape

(5,)

In [51]:
res=np.vstack((a,b)) #row wise vertically
res

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [52]:
res1=np.hstack((a,b))   #column wise horzontally
res1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])